function(add_fmt_lib NAME_ fmt_target)
    add_library(${NAME_} INTERFACE)
    target_link_libraries(${NAME_} INTERFACE flat_hash_base ${fmt_target})
    target_compile_definitions(${NAME_} INTERFACE FLAT_HASH_USE_FMTLIB)
    add_library(flat_hash::${NAME_} ALIAS ${NAME_})
endfunction()
