name: windows

on:
  push:
    branches: [master]
    paths-ignore:
      - "**/README.*"
      - "**/CONTRIBUTING.*"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**/README.*"
      - "**/CONTRIBUTING.*"

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: ".local"

jobs:
  build:
    runs-on: windows-2022
    name: ${{ github.workflow }}-${{ matrix.preset }}
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      fail-fast: false
      matrix:
        preset: ["ci-msvc", "ci-msvc-fmt"]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Find the number of threads (Windows)
        run: echo "::set-output name=THREADS::$((Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors)"
        id: number-of-threads
        shell: pwsh

      - uses: ./.github/build
        with:
          cmakePreset: ${{ matrix.preset }}
          threads: ${{ steps.number-of-threads.outputs.THREADS }}
